package com.ubuniworks.model;
// Generated May 10, 2016 7:07:11 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Biography generated by hbm2java
 */
@Entity
@Table(name = "biography", catalog = "kcaesn")
public class Biography implements java.io.Serializable {

	private Integer idbiography;
	private User user;
	private String aboutme;

	public Biography() {
	}

	public Biography(User user, String aboutme) {
		this.user = user;
		this.aboutme = aboutme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idbiography", unique = true, nullable = false)
	public Integer getIdbiography() {
		return this.idbiography;
	}

	public void setIdbiography(Integer idbiography) {
		this.idbiography = idbiography;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "aboutme", nullable = false)
	public String getAboutme() {
		return this.aboutme;
	}

	public void setAboutme(String aboutme) {
		this.aboutme = aboutme;
	}

}
