package com.ubuniworks.model;
// Generated May 4, 2016 2:02:58 PM by Hibernate Tools 5.1.0.Alpha1

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "kcaesn")
public class Comment implements java.io.Serializable {

	private Integer idcomment;
    private User user;
	private Comment comment;
	private Idea idea;
	private String commenttext;
    private Set<Comment> comments = new HashSet<Comment>(0);
	private String title;
	private Date datecreated;

	public Comment() {
	}

	public Comment(User user, String commenttext, String title, Date datecreated) {
		this.user = user;
		this.commenttext = commenttext;
		this.title = title;
		this.datecreated = datecreated;
	}

	public Comment(User user, Comment comment, Idea idea, String commenttext, String title, Date datecreated,
			Set<Comment> comments) {
		this.user = user;
		this.comment = comment;
		this.idea = idea;
		this.commenttext = commenttext;
		this.title = title;
		this.datecreated = datecreated;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
    @DocumentId
	@Column(name = "idcomment", unique = true, nullable = false)
	public Integer getIdcomment() {
		return this.idcomment;
	}

	public void setIdcomment(Integer idcomment) {
		this.idcomment = idcomment;
	}

    @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commentorid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

    @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idparentcomment")
	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

    @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ididea")
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "commenttext", nullable = false)
    @Field
	public String getCommenttext() {
		return this.commenttext;
	}

	public void setCommenttext(String commenttext) {
		this.commenttext = commenttext;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "comment")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@Column(name = "title", nullable = false)
	@Field
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", nullable = false, length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}


}
