package com.ubuniworks.model;
// Generated May 11, 2016 9:12:01 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Customersegment generated by hbm2java
 */
@Entity
@Table(name = "customersegment", catalog = "kcaesn")
public class Customersegment implements java.io.Serializable {

	private Integer idcustomersegment;
	private Idea idea;
	private String name;
	private String description;

	public Customersegment() {
	}

	public Customersegment(Idea idea, String name, String description) {
		this.idea = idea;
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcustomersegment", unique = true, nullable = false)
	public Integer getIdcustomersegment() {
		return this.idcustomersegment;
	}

	public void setIdcustomersegment(Integer idcustomersegment) {
		this.idcustomersegment = idcustomersegment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_ididea", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
