package com.ubuniworks.model;
// Generated May 10, 2016 7:07:11 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "kcaesn")
public class Experience implements java.io.Serializable {

	private Integer idexperience;
	private User user;
	private String place;
	private String activity;
	private String description;
	private Date startdate;
	private Date enddate;

	public Experience() {
	}

	public Experience(User user, String place, String activity, String description, Date startdate) {
		this.user = user;
		this.place = place;
		this.activity = activity;
		this.description = description;
		this.startdate = startdate;
	}

	public Experience(User user, String place, String activity, String description, Date startdate,
			Date enddate) {
		this.user = user;
		this.place = place;
		this.activity = activity;
		this.description = description;
		this.startdate = startdate;
		this.enddate = enddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idexperience", unique = true, nullable = false)
	public Integer getIdexperience() {
		return this.idexperience;
	}

	public void setIdexperience(Integer idexperience) {
		this.idexperience = idexperience;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "place", nullable = false)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "activity", nullable = false)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", nullable = false, length = 19)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 19)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

}
