package com.ubuniworks.model;
// Generated May 1, 2016 2:35:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Ideabody generated by hbm2java
 */
@Entity
@Table(name = "ideabody", catalog = "kcaesn")
public class Ideabody implements java.io.Serializable {

    private Integer idideabody;
    private String content;
    private Set<Idea> ideas = new HashSet<Idea>(0);

    public Ideabody() {
    }

    public Ideabody(int idideabody, String content) {
        this.idideabody = idideabody;
        this.content = content;
    }

    public Ideabody(int idideabody, String content, Set<Idea> ideas) {
        this.idideabody = idideabody;
        this.content = content;
        this.ideas = ideas;
    }

    @Id

    @Column(name = "idideabody", unique = true, nullable = false)
    public Integer getIdideabody() {
        return this.idideabody;
    }

    public void setIdideabody(Integer idideabody) {
        this.idideabody = idideabody;
    }

    @Column(name = "content", nullable = false)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ideabody")
    public Set<Idea> getIdeas() {
        return this.ideas;
    }

    public void setIdeas(Set<Idea> ideas) {
        this.ideas = ideas;
    }

}
