package com.ubuniworks.model;
// Generated May 4, 2016 2:02:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Milestone generated by hbm2java
 */
@Entity
@Table(name = "milestone", catalog = "kcaesn")
public class Milestone implements java.io.Serializable {

	private Integer idmilestone;
	private Idea idea;
	private Milestone milestone;
	private String description;
	private Date duedate;
	private Date datecreated;
	private Set<Milestone> milestones = new HashSet<Milestone>(0);

	public Milestone() {
	}

	public Milestone(Idea idea, String description, Date duedate, Date datecreated) {
		this.idea = idea;
		this.description = description;
		this.duedate = duedate;
		this.datecreated = datecreated;
	}

	public Milestone(Idea idea, Milestone milestone, String description, Date duedate, Date datecreated,
			Set<Milestone> milestones) {
		this.idea = idea;
		this.milestone = milestone;
		this.description = description;
		this.duedate = duedate;
		this.datecreated = datecreated;
		this.milestones = milestones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmilestone", unique = true, nullable = false)
	public Integer getIdmilestone() {
		return this.idmilestone;
	}

	public void setIdmilestone(Integer idmilestone) {
		this.idmilestone = idmilestone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ididea", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddependencymilestone")
	public Milestone getMilestone() {
		return this.milestone;
	}

	public void setMilestone(Milestone milestone) {
		this.milestone = milestone;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "duedate", nullable = false, length = 19)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", nullable = false, length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "milestone")
	public Set<Milestone> getMilestones() {
		return this.milestones;
	}

	public void setMilestones(Set<Milestone> milestones) {
		this.milestones = milestones;
	}

}
