package com.ubuniworks.model;
// Generated May 11, 2016 9:12:01 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name = "resources", catalog = "kcaesn")
public class Resources implements java.io.Serializable {

	private Integer idresources;
	private Idea idea;
	private String name;
	private String description;

	public Resources() {
	}

	public Resources(Idea idea, String name, String description) {
		this.idea = idea;
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idresources", unique = true, nullable = false)
	public Integer getIdresources() {
		return this.idresources;
	}

	public void setIdresources(Integer idresources) {
		this.idresources = idresources;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_ididea", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
