package com.ubuniworks.model;
// Generated May 10, 2016 7:07:11 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "kcaesn")
public class Tag implements java.io.Serializable {

	private Integer idtag;
	private String name;
	private String description;
	private Set<com.ubuniworks.model.Idea> ideas = new HashSet<com.ubuniworks.model.Idea>(0);

	public Tag() {
	}

	public Tag(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Tag(String name, String description, Set<com.ubuniworks.model.Idea> ideas) {
		this.name = name;
		this.description = description;
		this.ideas = ideas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtag", unique = true, nullable = false)
	public Integer getIdtag() {
		return this.idtag;
	}

	public void setIdtag(Integer idtag) {
		this.idtag = idtag;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "idea_has_tag", catalog = "kcaesn", joinColumns = {
			@JoinColumn(name = "tag_idtag", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idea_ididea", nullable = false, updatable = false) })
	public Set<com.ubuniworks.model.Idea> getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set<com.ubuniworks.model.Idea> ideas) {
		this.ideas = ideas;
	}

}
